weights: yolov4.weights
cfg: cfg/1-yolov4-tiny.cfg
data: ./data/1fiftyone.yaml
hyp: data/hyp.scratch.yaml
epochs: 300
batch_size: 64
img_size:
- 256
- 256
rect: false
resume: false
nosave: false
notest: false
noautoanchor: false
evolve: false
bucket: ''
cache_images: false
image_weights: false
device: '0'
multi_scale: false
single_cls: true
adam: false
sync_bn: false
local_rank: -1
log_imgs: 16
workers: 8
project: runs/train
name: yolov4-single-1fiftyone
exist_ok: false
total_batch_size: 64
world_size: 1
global_rank: -1
save_dir: runs/train/yolov4-single-1fiftyone
