weights: yolov4.weights
cfg: cfg/4-yolov4-tiny.cfg
data: ./data/4grass.yaml
hyp: data/hyp.scratch.yaml
epochs: 200
batch_size: 16
img_size:
- 640
- 640
rect: false
resume: false
nosave: false
notest: false
noautoanchor: false
evolve: false
bucket: ''
cache_images: false
image_weights: false
device: '0'
multi_scale: false
single_cls: false
adam: false
sync_bn: false
local_rank: -1
log_imgs: 16
workers: 8
project: runs/train
name: 4grass-scratch-v2
exist_ok: false
total_batch_size: 16
world_size: 1
global_rank: -1
save_dir: runs/train/4grass-scratch-v2
